using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Options;
using Recurvos.Application.Abstractions;
using Recurvos.Domain.Entities;
using Recurvos.Infrastructure.Configuration;
using Recurvos.Infrastructure.Persistence;
using Recurvos.Infrastructure.Templates;

namespace Recurvos.Infrastructure.Services;

public sealed class PlatformOwnerNotificationService(
    AppDbContext dbContext,
    IEmailSender emailSender,
    IOptions<AppUrlOptions> appUrlOptions)
{
    private readonly AppUrlOptions _appUrlOptions = appUrlOptions.Value;

    public async Task TryNotifyNewSignupAsync(User user, Company company, CancellationToken cancellationToken = default)
    {
        var recipientEmail = await ResolveRecipientEmailAsync(cancellationToken);
        if (string.IsNullOrWhiteSpace(recipientEmail))
        {
            return;
        }

        var actionUrl = $"{_appUrlOptions.WebBaseUrl.TrimEnd('/')}/subscribers";
        var body = EmailTemplateRenderer.RenderActionEmail(
            "New signup",
            $"New signup from {company.Name}",
            $"{user.FullName} registered a new subscriber account for {company.Name}. Review the signup details in the platform console.",
            "Open subscribers",
            actionUrl,
            [
                $"Company: {company.Name}",
                $"Registration number: {company.RegistrationNumber}",
                $"Company email: {company.Email}",
                $"User email: {user.Email}",
                $"Selected package: {company.SelectedPackage ?? "Not selected"}"
            ],
            "This notification was generated by Recurvos signup monitoring.");

        try
        {
            await emailSender.SendAsync(recipientEmail.Trim(), $"New signup: {company.Name}", body, cancellationToken: cancellationToken);
        }
        catch (InvalidOperationException)
        {
        }
    }

    public async Task TryNotifyNewPaymentAsync(Guid paymentId, CancellationToken cancellationToken = default)
    {
        var recipientEmail = await ResolveRecipientEmailAsync(cancellationToken);
        if (string.IsNullOrWhiteSpace(recipientEmail))
        {
            return;
        }

        var payment = await dbContext.Payments
            .Include(x => x.Invoice)
                .ThenInclude(x => x!.Customer)
            .FirstOrDefaultAsync(x => x.Id == paymentId, cancellationToken);

        if (payment?.Invoice is null || payment.Status != Domain.Enums.PaymentStatus.Succeeded)
        {
            return;
        }

        var companyName = await dbContext.Companies
            .Where(x => x.Id == payment.CompanyId)
            .Select(x => x.Name)
            .FirstOrDefaultAsync(cancellationToken) ?? "Unknown company";
        var customerName = payment.Invoice.Customer?.Name ?? "Unknown customer";
        var actionUrl = $"{_appUrlOptions.WebBaseUrl.TrimEnd('/')}/payments?tab=records";
        var paidAtLabel = (payment.PaidAtUtc ?? payment.CreatedAtUtc).ToString("dd MMM yyyy HH:mm 'UTC'");
        var reference = payment.ExternalPaymentId ?? payment.GatewayTransactionId ?? payment.GatewaySettlementRef ?? "Not provided";
        var body = EmailTemplateRenderer.RenderActionEmail(
            "New payment",
            $"Payment received for {payment.Invoice.InvoiceNumber}",
            $"{companyName} recorded a new payment. Review the payment details and linked invoice in the platform console.",
            "Open payments",
            actionUrl,
            [
                $"Company: {companyName}",
                $"Invoice: {payment.Invoice.InvoiceNumber}",
                $"Customer: {customerName}",
                $"Amount: {payment.Currency} {payment.Amount:0.00}",
                $"Method: {payment.GatewayName}",
                $"Paid at: {paidAtLabel}",
                $"Reference: {reference}"
            ],
            "This notification was generated by Recurvos payment monitoring.");

        try
        {
            await emailSender.SendAsync(recipientEmail.Trim(), $"New payment: {payment.Invoice.InvoiceNumber}", body, cancellationToken: cancellationToken);
        }
        catch (InvalidOperationException)
        {
        }
    }

    private async Task<string?> ResolveRecipientEmailAsync(CancellationToken cancellationToken)
    {
        return await dbContext.Companies
            .Where(x => x.IsPlatformAccount)
            .Select(x => x.InvoiceSettings != null ? x.InvoiceSettings.FeedbackNotificationEmail : null)
            .FirstOrDefaultAsync(cancellationToken);
    }
}
