import { formatCurrency } from "./format";

type DocumentRow = { cells: Array<string | number>; numeric?: number[] };
type DocumentTotal = { label: string; value: number; emphasis?: boolean };

export type BusinessDocumentPdf = {
  companyName?: string;
  title: string;
  number: string;
  partyLabel: string;
  partyName: string;
  currency: string;
  metadata: Array<Array<string | undefined | null>>;
  headings: string[];
  rows: DocumentRow[];
  totals?: DocumentTotal[];
  notes?: string | null;
  acknowledgement?: { preparedBy: string; receivedBy: string };
};

function escapeHtml(value: string | number) {
  return String(value).replaceAll("&", "&amp;").replaceAll("<", "&lt;").replaceAll(">", "&gt;").replaceAll('"', "&quot;").replaceAll("'", "&#39;");
}

export function openBusinessDocumentPdf(document: BusinessDocumentPdf) {
  const popup = window.open("", "_blank", "width=960,height=720");
  if (!popup) return;
  popup.opener = null;
  const metadata = document.metadata.filter(([, value]) => value).map(([label, value]) => `<div><span>${escapeHtml(label ?? "")}</span><strong>${escapeHtml(value ?? "")}</strong></div>`).join("");
  const rows = document.rows.map((row) => `<tr>${row.cells.map((cell, index) => `<td class="${row.numeric?.includes(index) ? "number" : ""}">${escapeHtml(cell)}</td>`).join("")}</tr>`).join("");
  const totals = document.totals?.map((total) => `<div class="total ${total.emphasis ? "emphasis" : ""}"><span>${escapeHtml(total.label)}</span><strong>${escapeHtml(formatCurrency(total.value, document.currency))}</strong></div>`).join("") ?? "";
  const acknowledgement = document.acknowledgement ? `<section class="ack"><div><strong>${escapeHtml(document.acknowledgement.preparedBy)}</strong><p>Name: ______________________________</p><p>Signature: ___________________________</p><p>Date: _______________________________</p></div><div><strong>${escapeHtml(document.acknowledgement.receivedBy)}</strong><p>Name: ______________________________</p><p>Signature: ___________________________</p><p>Date: _______________________________</p></div></section>` : "";
  popup.document.write(`<!doctype html><html><head><meta charset="utf-8" /><title>${escapeHtml(document.number)}</title><style>@page{size:A4;margin:16mm}*{box-sizing:border-box}body{font-family:Arial,sans-serif;color:#172b4d;font-size:11px;margin:0}.header{display:flex;justify-content:space-between;gap:24px;border-bottom:2px solid #2563eb;padding-bottom:16px}.company{max-width:56%}.company h1{font-size:20px;margin:0 0 5px}.company p,.notes p{color:#526581;margin:3px 0}.doc{text-align:right}.doc p{margin:0;color:#2563eb;font-size:11px;font-weight:700;letter-spacing:.1em}.doc h2{font-size:23px;margin:5px 0}.party-meta{display:grid;grid-template-columns:1fr 1fr;gap:26px;margin:22px 0}.party{border-left:3px solid #bfdbfe;padding-left:10px}.party span,.meta span{display:block;color:#64748b;font-size:9px;font-weight:700;letter-spacing:.08em;text-transform:uppercase}.party strong{display:block;margin-top:5px;font-size:13px}.meta{display:grid;grid-template-columns:1fr 1fr;gap:8px 18px}.meta div{display:flex;justify-content:space-between;gap:8px;border-bottom:1px solid #e2e8f0;padding-bottom:4px}.meta strong{font-size:10px;text-align:right}table{width:100%;border-collapse:collapse;margin-top:8px}th{background:#eff6ff;color:#315b96;padding:9px 7px;text-align:left;font-size:9px;letter-spacing:.06em;text-transform:uppercase}td{padding:9px 7px;border-bottom:1px solid #e5edf6;vertical-align:top}.number{text-align:right;white-space:nowrap}.totals{width:290px;margin:20px 0 0 auto}.total{display:flex;justify-content:space-between;padding:7px 0;border-bottom:1px solid #dbe4f0}.total.emphasis{border-top:2px solid #2563eb;border-bottom:0;color:#123a72;font-size:13px;padding-top:9px}.notes{margin-top:26px;padding-top:10px;border-top:1px solid #dbe4f0}.notes strong{font-size:10px;text-transform:uppercase;letter-spacing:.08em}.ack{display:grid;grid-template-columns:1fr 1fr;gap:46px;margin-top:36px}.ack div{border-top:1px solid #94a3b8;padding-top:8px}.ack p{margin:12px 0;color:#526581}@media print{body{print-color-adjust:exact;-webkit-print-color-adjust:exact}}</style></head><body><header class="header"><div class="company"><h1>${escapeHtml(document.companyName || "Recurvos")}</h1><p>Business document generated by Recurvos</p></div><div class="doc"><p>${escapeHtml(document.title)}</p><h2>${escapeHtml(document.number)}</h2></div></header><section class="party-meta"><div class="party"><span>${escapeHtml(document.partyLabel)}</span><strong>${escapeHtml(document.partyName)}</strong></div><div class="meta">${metadata}</div></section><table><thead><tr>${document.headings.map((heading) => `<th>${escapeHtml(heading)}</th>`).join("")}</tr></thead><tbody>${rows}</tbody></table>${totals ? `<section class="totals">${totals}</section>` : ""}${document.notes ? `<section class="notes"><strong>Notes</strong><p>${escapeHtml(document.notes)}</p></section>` : ""}${acknowledgement}<script>window.onload=()=>window.print()</script></body></html>`);
  popup.document.close();
}
