// <auto-generated />
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Recurvos.Infrastructure.Persistence;

#nullable disable

namespace Recurvos.Infrastructure.Persistence.Migrations;

[DbContext(typeof(AppDbContext))]
[Migration("20260723120000_AddSubscriberAccountBillingProfile")]
public partial class AddSubscriberAccountBillingProfile
{
}
