import { useEffect, useMemo, useState } from "react";
import { useNavigate, useSearchParams } from "react-router-dom";
import { EmptyTableRow } from "../components/EmptyTableRow";
import { HelperText } from "../components/ui/HelperText";
import { api } from "../lib/api";
import { formatCurrency } from "../lib/format";
import type { Account, CompanyLookup, GeneralLedgerReport, MasterDataSnapshot } from "../types";

export function GeneralLedgerPage() {
  const navigate = useNavigate(); const [searchParams] = useSearchParams(); const [companies, setCompanies] = useState<CompanyLookup[]>([]); const [accounts, setAccounts] = useState<Account[]>([]); const [companyId, setCompanyId] = useState(searchParams.get("companyId") ?? ""); const [accountId, setAccountId] = useState(searchParams.get("accountId") ?? ""); const [from, setFrom] = useState(searchParams.get("from") ?? new Date(new Date().getFullYear(), new Date().getMonth(), 1).toISOString().slice(0, 10)); const [to, setTo] = useState(searchParams.get("to") ?? new Date().toISOString().slice(0, 10)); const [search, setSearch] = useState(""); const [report, setReport] = useState<GeneralLedgerReport | null>(null); const [error, setError] = useState("");
  useEffect(() => { void Promise.all([api.get<CompanyLookup[]>("/companies"), api.get<MasterDataSnapshot>("/master-data")]).then(([companyList, master]) => { setCompanies(companyList); setAccounts(master.accounts); setCompanyId(current => current || companyList[0]?.id || ""); }).catch(e => setError(e instanceof Error ? e.message : "Unable to load filters.")); }, []);
  const query = useMemo(() => { const p = new URLSearchParams({ companyId, fromDateUtc: new Date(`${from}T00:00:00Z`).toISOString(), toDateUtc: new Date(`${to}T00:00:00Z`).toISOString() }); if (accountId) p.set("accountId", accountId); if (search.trim()) p.set("search", search.trim()); return p; }, [companyId, from, to, accountId, search]);
  async function load() { if (!companyId) return; try { setError(""); setReport(await api.get<GeneralLedgerReport>(`/accounting/reports/general-ledger?${query}`)); } catch (e) { setError(e instanceof Error ? e.message : "Unable to load general ledger."); } }
  useEffect(() => { void load(); }, [query]);
  async function exportCsv() { try { const file = await api.download(`/accounting/reports/general-ledger/csv?${query}`); const url = URL.createObjectURL(file.blob); const a = document.createElement("a"); a.href = url; a.download = file.fileName ?? "general-ledger.csv"; a.click(); URL.revokeObjectURL(url); } catch (e) { setError(e instanceof Error ? e.message : "Unable to export general ledger."); } }
  return <div className="page"><header className="page-header"><div className="page-header-copy"><h2>General Ledger</h2><p className="muted">Posted journal entries only</p></div><div className="contact-page-actions"><button type="button" className="button button-secondary" onClick={() => window.print()}>Print</button><button type="button" className="button button-primary" onClick={() => void exportCsv()}>Export CSV</button></div></header>{error ? <HelperText tone="error">{error}</HelperText> : null}<div className="catalog-toolbar card subtle-card"><select value={companyId} onChange={e => setCompanyId(e.target.value)}>{companies.map(x => <option key={x.id} value={x.id}>{x.name}</option>)}</select><select value={accountId} onChange={e => setAccountId(e.target.value)}><option value="">All accounts</option>{accounts.filter(x => x.isActive).map(x => <option key={x.id} value={x.id}>{x.code} · {x.name}</option>)}</select><input type="date" className="text-input" value={from} onChange={e => setFrom(e.target.value)} /><input type="date" className="text-input" value={to} onChange={e => setTo(e.target.value)} /><input className="text-input" value={search} onChange={e => setSearch(e.target.value)} placeholder="Journal, reference, or description" /></div>{report ? <>{report.accounts.length === 0 ? <section className="card"><p className="muted">No posted journal activity in this period.</p></section> : report.accounts.map(account => <section className="card" key={account.accountId}><div className="card-section-header"><div><h3 className="section-title">{account.accountCode} · {account.accountName}</h3><p className="muted">Opening {formatCurrency(account.openingBalance, report.currency)} · Closing {formatCurrency(account.closingBalance, report.currency)}</p></div></div><div className="table-scroll table-scroll-bounded"><table className="catalog-table"><thead><tr><th>Date</th><th>Journal</th><th>Reference</th><th>Description</th><th>Debit</th><th>Credit</th><th>Balance</th></tr></thead><tbody>{account.transactions.length === 0 ? <EmptyTableRow colSpan={7} title="No period transactions" description="The opening balance is carried from earlier posted journals." /> : account.transactions.map(line => <tr key={`${line.journalEntryId}-${line.journalNumber}`}><td>{new Date(line.journalDateUtc).toLocaleDateString()}</td><td><button className="table-link-button" type="button" onClick={() => navigate(`/finance/journal-entries/${line.journalEntryId}`)}>{line.journalNumber}</button></td><td>{line.referenceNo}</td><td>{line.description}</td><td>{formatCurrency(line.debitAmount, report.currency)}</td><td>{formatCurrency(line.creditAmount, report.currency)}</td><td>{formatCurrency(line.runningBalance, report.currency)}</td></tr>)}</tbody></table></div></section>)}</> : <section className="card"><p className="muted">Loading ledger...</p></section>}</div>;
}
