import { useEffect, useMemo, useState } from "react";
import { useNavigate } from "react-router-dom";
import { ConfirmModal } from "../components/ConfirmModal";
import { EmptyTableRow } from "../components/EmptyTableRow";
import { RowActionMenu } from "../components/RowActionMenu";
import { TablePagination } from "../components/TablePagination";
import { useClientPagination } from "../hooks/useClientPagination";
import { api } from "../lib/api";
import { formatCurrency } from "../lib/format";
import type { CompanyLookup, JournalEntryListItem } from "../types";

export function JournalEntriesPage() {
  const navigate = useNavigate(); const [items, setItems] = useState<JournalEntryListItem[]>([]); const [companies, setCompanies] = useState<CompanyLookup[]>([]); const [search, setSearch] = useState(""); const [companyId, setCompanyId] = useState(""); const [status, setStatus] = useState(""); const [confirm, setConfirm] = useState<{ title: string; description: string; action: () => Promise<void> } | null>(null);
  async function load() { const query = new URLSearchParams(); if (search.trim()) query.set("search", search.trim()); if (companyId) query.set("companyId", companyId); if (status) query.set("status", status); const [journals, companyList] = await Promise.all([api.get<JournalEntryListItem[]>(`/accounting/journal-entries${query.size ? `?${query}` : ""}`), api.get<CompanyLookup[]>("/companies")]); setItems(journals); setCompanies(companyList); }
  useEffect(() => { void load(); }, [search, companyId, status]); const pagination = useClientPagination(useMemo(() => items, [items]), [search, companyId, status]);
  function actions(item: JournalEntryListItem) { return [{ label: "View", onClick: () => navigate(`/finance/journal-entries/${item.id}`) }, ...(item.status === "Draft" ? [{ label: "Edit", onClick: () => navigate(`/finance/journal-entries/${item.id}/edit`) }, { label: "Post", onClick: () => setConfirm({ title: "Post journal entry", description: `Post ${item.journalNumber}? Posted journals cannot be edited.`, action: async () => { await api.post(`/accounting/journal-entries/${item.id}/post`, {}); setConfirm(null); await load(); } }) }, { label: "Cancel", onClick: () => setConfirm({ title: "Cancel journal entry", description: `Cancel ${item.journalNumber}?`, action: async () => { await api.post(`/accounting/journal-entries/${item.id}/cancel`, {}); setConfirm(null); await load(); } }) }, { label: "Delete", tone: "danger" as const, onClick: () => setConfirm({ title: "Delete journal entry", description: `Delete draft ${item.journalNumber}?`, action: async () => { await api.delete(`/accounting/journal-entries/${item.id}`); setConfirm(null); await load(); } }) }] : []), ...(item.status === "Posted" && !item.reversedByJournalEntryId ? [{ label: "Reverse", tone: "danger" as const, onClick: () => setConfirm({ title: "Reverse journal entry", description: `Create and post a reversal for ${item.journalNumber}?`, action: async () => { await api.post(`/accounting/journal-entries/${item.id}/reverse`, {}); setConfirm(null); await load(); } }) }] : [])]; }
  return <div className="page"><header className="page-header"><div className="page-header-copy"><h2>Journal Entries</h2></div><button type="button" className="button button-primary" onClick={() => navigate("/finance/journal-entries/new")}>Create journal entry</button></header><div className="catalog-toolbar card subtle-card"><input className="text-input" value={search} onChange={(e) => setSearch(e.target.value)} placeholder="Search number, reference, or description" /><select value={companyId} onChange={(e) => setCompanyId(e.target.value)}><option value="">All companies</option>{companies.map(x => <option key={x.id} value={x.id}>{x.name}</option>)}</select><select value={status} onChange={(e) => setStatus(e.target.value)}><option value="">All statuses</option>{["Draft", "Posted", "Reversed", "Cancelled"].map(x => <option key={x}>{x}</option>)}</select></div><section className="card"><div className="table-scroll table-scroll-bounded"><table className="catalog-table"><thead><tr><th>Journal No</th><th>Date</th><th>Company</th><th>Description</th><th>Debit</th><th>Credit</th><th>Status</th><th>Action</th></tr></thead><tbody>{items.length === 0 ? <EmptyTableRow colSpan={8} title="No journal entries yet" description="Create a balanced manual journal entry." actions={<button type="button" className="button button-primary" onClick={() => navigate("/finance/journal-entries/new")}>Create journal entry</button>} /> : pagination.pagedItems.map(x => <tr key={x.id}><td>{x.journalNumber}</td><td>{new Date(x.journalDateUtc).toLocaleDateString()}</td><td>{x.companyName}</td><td>{x.description}</td><td>{formatCurrency(x.totalDebit, x.currency)}</td><td>{formatCurrency(x.totalCredit, x.currency)}</td><td><span className="status-badge">{x.status}</span></td><td className="actions-cell"><RowActionMenu items={actions(x)} /></td></tr>)}</tbody></table></div><TablePagination currentPage={pagination.currentPage} pageSize={pagination.pageSize} totalItems={items.length} totalPages={pagination.totalPages} rangeStart={pagination.rangeStart} rangeEnd={pagination.rangeEnd} onPageChange={pagination.setCurrentPage} onPageSizeChange={pagination.setPageSize} /></section><ConfirmModal open={!!confirm} title={confirm?.title ?? ""} description={confirm?.description ?? ""} confirmLabel="Confirm" onConfirm={async () => { await confirm?.action(); }} onCancel={() => setConfirm(null)} /></div>;
}
