import { useEffect, useState } from "react";
import { useNavigate, useParams } from "react-router-dom";
import { ConfirmModal } from "../components/ConfirmModal";
import { api } from "../lib/api";
import { formatCurrency } from "../lib/format";
import type { JournalEntry } from "../types";

export function JournalEntryDetailsPage() {
  const { id } = useParams(); const navigate = useNavigate(); const [journal, setJournal] = useState<JournalEntry | null>(null); const [confirm, setConfirm] = useState<{ title: string; description: string; action: () => Promise<void> } | null>(null);
  async function load() { if (id) setJournal(await api.get<JournalEntry>(`/accounting/journal-entries/${id}`)); } useEffect(() => { void load(); }, [id]); if (!journal) return <div className="page"><section className="card"><p className="muted">Loading...</p></section></div>;
  const debit = journal.lines.reduce((s, x) => s + x.debitAmount, 0); const credit = journal.lines.reduce((s, x) => s + x.creditAmount, 0);
  return <div className="page"><header className="page-header"><div className="page-header-copy"><h2>{journal.journalNumber}</h2><p className="muted">{journal.description}</p></div><div className="contact-page-actions"><button type="button" className="button button-secondary" onClick={() => navigate("/finance/journal-entries")}>Back to journals</button>{journal.status === "Draft" ? <><button type="button" className="button button-secondary" onClick={() => navigate(`/finance/journal-entries/${journal.id}/edit`)}>Edit</button><button type="button" className="button button-primary" onClick={() => setConfirm({ title: "Post journal entry", description: "Post this journal? It will become locked.", action: async () => { await api.post(`/accounting/journal-entries/${journal.id}/post`, {}); setConfirm(null); await load(); } })}>Post</button></> : null}{journal.status === "Posted" && !journal.reversedByJournalEntryId ? <button type="button" className="button button-secondary" onClick={() => setConfirm({ title: "Reverse journal entry", description: "Create and post the offsetting reversal?", action: async () => { await api.post(`/accounting/journal-entries/${journal.id}/reverse`, {}); setConfirm(null); await load(); } })}>Reverse</button> : null}</div></header><section className="card"><div className="page-meta-row"><div className="page-meta-chips"><span className="page-meta-chip">Status <strong>{journal.status}</strong></span><span className="page-meta-chip">Date <strong>{new Date(journal.journalDateUtc).toLocaleDateString()}</strong></span>{journal.referenceNo ? <span className="page-meta-chip">Reference <strong>{journal.referenceNo}</strong></span> : null}</div></div><div className="table-scroll table-scroll-bounded"><table className="catalog-table"><thead><tr><th>Account</th><th>Description</th><th className="numeric-cell">Debit</th><th className="numeric-cell">Credit</th></tr></thead><tbody>{journal.lines.map(x => <tr key={x.id}><td>{x.accountCode} · {x.accountName}</td><td>{x.description}</td><td className="numeric-cell">{formatCurrency(x.debitAmount, "MYR")}</td><td className="numeric-cell">{formatCurrency(x.creditAmount, "MYR")}</td></tr>)}</tbody><tfoot><tr><th colSpan={2}>Total</th><th className="numeric-cell">{formatCurrency(debit, "MYR")}</th><th className="numeric-cell">{formatCurrency(credit, "MYR")}</th></tr></tfoot></table></div></section><ConfirmModal open={!!confirm} title={confirm?.title ?? ""} description={confirm?.description ?? ""} confirmLabel="Confirm" onConfirm={async () => { await confirm?.action(); }} onCancel={() => setConfirm(null)} /></div>;
}
