import { useEffect, useMemo, useState } from "react";
import { useLocation, useNavigate, useSearchParams } from "react-router-dom";
import { ConfirmModal } from "../components/ConfirmModal";
import { FormPageHeader } from "../components/ui/FormPageHeader";
import { TransactionFormCard } from "../components/ui/TransactionFormCard";
import { api } from "../lib/api";
import { formatCurrency } from "../lib/format";
import type { PurchaseBill } from "../types";

export function PurchasePaymentFormPage() {
  const navigate = useNavigate(); const location = useLocation(); const [params] = useSearchParams();
  const sourceBillId = params.get("purchaseBillId") ?? ""; const initialSupplier = params.get("supplierId") ?? "";
  const [bills, setBills] = useState<PurchaseBill[]>([]); const [supplier, setSupplier] = useState(initialSupplier); const [amounts, setAmounts] = useState<Record<string, string>>({});
  const [paymentDateUtc, setPaymentDateUtc] = useState(() => new Date().toISOString().slice(0, 10)); const [referenceNo, setReferenceNo] = useState(""); const [notes, setNotes] = useState(""); const [pendingSupplier, setPendingSupplier] = useState<string | null>(null); const [submitting, setSubmitting] = useState(false);
  useEffect(() => { void api.get<PurchaseBill[]>("/purchases/bills").then((items) => { setBills(items); const source = items.find((bill) => bill.id === sourceBillId && bill.contactId === initialSupplier); if (source) setAmounts({ [source.id]: String(source.amountDue) }); }); }, [initialSupplier, sourceBillId]);
  const suppliers = useMemo(() => Array.from(new Map(bills.map((bill) => [bill.contactId, bill.contactName])).entries()), [bills]); const rows = useMemo(() => bills.filter((bill) => bill.contactId === supplier && bill.amountDue > 0 && bill.status !== "Cancelled"), [bills, supplier]);
  const selected = rows.filter((bill) => bill.id in amounts); const total = Object.values(amounts).reduce((sum, value) => sum + (Number(value) || 0), 0); const invalid = selected.some((bill) => !Number.isFinite(Number(amounts[bill.id])) || Number(amounts[bill.id]) <= 0 || Number(amounts[bill.id]) > bill.amountDue); const valid = selected.length > 0 && !invalid;
  function changeSupplier(next: string) { if (next === supplier) return; if (Object.keys(amounts).length) { setPendingSupplier(next); return; } setSupplier(next); }
  async function submit() { const allocations = rows.filter((bill) => Number(amounts[bill.id]) > 0).map((bill) => ({ purchaseBillId: bill.id, amount: Number(amounts[bill.id]) })); if (!allocations.length) return; setSubmitting(true); try { await api.post("/purchases/payments", { paymentDateUtc: new Date(`${paymentDateUtc}T00:00:00Z`).toISOString(), currency: rows[0]?.currency, referenceNo: referenceNo.trim(), notes: notes.trim(), allocations }); navigate("/purchases/payments"); } finally { setSubmitting(false); } }
  return <div className="page"><FormPageHeader backLabel="Back to Payments" backHref="/purchases/payments" breadcrumbs={<><span>Payments</span><span>/</span><span>New Payment</span></>} /><TransactionFormCard title="Payment details" description="Record and allocate a supplier payment.">
    <section className="card"><div className="master-data-form-grid master-data-form-grid-wide"><label className="form-label master-data-form-wide">Supplier<select value={supplier} onChange={(event) => changeSupplier(event.target.value)}><option value="">Select supplier</option>{suppliers.map(([id, name]) => <option key={id} value={id}>{name}</option>)}</select></label><label className="form-label">Payment date<input className="text-input" type="date" value={paymentDateUtc} onChange={(event) => setPaymentDateUtc(event.target.value)} /></label><label className="form-label">Reference<input className="text-input" value={referenceNo} onChange={(event) => setReferenceNo(event.target.value)} /></label><label className="form-label master-data-form-wide">Notes<input className="text-input" value={notes} onChange={(event) => setNotes(event.target.value)} /></label></div></section>
    <section className="card"><div className="card-section-header"><div className="section-header-cluster"><h3 className="section-title">Bill Allocations</h3><p className="muted">Select outstanding bills and enter the amount to allocate.</p></div>{rows.length > 1 ? <button type="button" className="button button-secondary button-compact" onClick={() => setAmounts(Object.fromEntries(rows.map((bill) => [bill.id, String(bill.amountDue)])))}>Select all</button> : null}</div>{!supplier ? <p className="muted">Select a supplier to view outstanding bills.</p> : rows.length === 0 ? <div className="empty-state"><h4>No outstanding bills</h4><p>This supplier has no bills available for payment.</p></div> : <><div className="table-scroll table-scroll-bounded"><table className="catalog-table"><thead><tr><th>Select</th><th>Bill</th><th>Due Date</th><th>Outstanding</th><th>Amount Paid</th></tr></thead><tbody>{rows.map((bill) => <tr key={bill.id}><td><input type="checkbox" checked={bill.id in amounts} onChange={(event) => setAmounts((current) => { const next = { ...current }; if (event.target.checked) next[bill.id] = String(bill.amountDue); else delete next[bill.id]; return next; })} /></td><td><button type="button" className="inline-link" onClick={() => navigate(`/purchases/bills/${bill.id}`, { state: { backgroundLocation: location } })}>{bill.purchaseBillNumber}</button></td><td>{new Date(bill.dueDateUtc).toLocaleDateString()}</td><td>{formatCurrency(bill.amountDue, bill.currency)}</td><td><input className="text-input" inputMode="decimal" disabled={!(bill.id in amounts)} value={amounts[bill.id] ?? ""} onChange={(event) => { const value = event.target.value; if (value === "" || /^\d*(?:\.\d*)?$/.test(value)) setAmounts((current) => ({ ...current, [bill.id]: value })); }} /></td></tr>)}</tbody></table></div><div className="page-meta-row page-meta-row-inline payment-allocation-total"><span>{selected.length} bill{selected.length === 1 ? "" : "s"} selected<br />Payment total</span><strong>{formatCurrency(total, rows[0]?.currency ?? "")}</strong></div></>}</section>
    <div className="contact-page-actions form-footer-create"><span>{!selected.length ? "Select at least one bill to continue." : invalid ? "Enter a valid payment amount to continue." : ""}</span><button type="button" className="button button-secondary" disabled={submitting} onClick={() => navigate("/purchases/payments")}>Cancel</button><button type="button" className="button button-primary" disabled={!supplier || !valid || submitting} onClick={() => void submit()}>{submitting ? "Posting..." : "Post payment"}</button></div>
  </TransactionFormCard><ConfirmModal open={pendingSupplier !== null} title="Change supplier?" description="Changing the supplier will clear the current bill allocations." confirmLabel="Change supplier" onConfirm={async () => { setSupplier(pendingSupplier ?? ""); setAmounts({}); setPendingSupplier(null); }} onCancel={() => setPendingSupplier(null)} /></div>;
}
