import { useEffect, useMemo, useState } from "react";
import { EmptyTableRow } from "../components/EmptyTableRow";
import { HelperText } from "../components/ui/HelperText";
import { api } from "../lib/api";
import { resolveActiveCompanyId } from "../lib/auth";
import { formatCurrency } from "../lib/format";
import type { CompanyLookup, TrialBalanceReport } from "../types";

export function TrialBalancePage() {
  const [companies, setCompanies] = useState<CompanyLookup[]>([]); const [companyId, setCompanyId] = useState(""); const [from, setFrom] = useState(new Date(new Date().getFullYear(), new Date().getMonth(), 1).toISOString().slice(0, 10)); const [to, setTo] = useState(new Date().toISOString().slice(0, 10)); const [report, setReport] = useState<TrialBalanceReport | null>(null); const [error, setError] = useState("");
  useEffect(() => { void api.get<CompanyLookup[]>("/companies").then(list => { setCompanies(list); setCompanyId(resolveActiveCompanyId(list)); }).catch(e => setError(e instanceof Error ? e.message : "Unable to load companies.")); }, []);
  const query = useMemo(() => new URLSearchParams({ companyId, fromDateUtc: new Date(`${from}T00:00:00Z`).toISOString(), toDateUtc: new Date(`${to}T00:00:00Z`).toISOString() }), [companyId, from, to]);
  async function load() { if (!companyId) return; try { setError(""); setReport(await api.get<TrialBalanceReport>(`/accounting/reports/trial-balance?${query}`)); } catch (e) { setError(e instanceof Error ? e.message : "Unable to load trial balance."); } }
  useEffect(() => { void load(); }, [query]);
  async function exportCsv() { try { const file = await api.download(`/accounting/reports/trial-balance/csv?${query}`); const url = URL.createObjectURL(file.blob); const a = document.createElement("a"); a.href = url; a.download = file.fileName ?? "trial-balance.csv"; a.click(); URL.revokeObjectURL(url); } catch (e) { setError(e instanceof Error ? e.message : "Unable to export trial balance."); } }
  return <div className="page"><header className="page-header"><div className="page-header-copy"><h2>Trial Balance</h2><p className="muted">Posted journal entries only</p></div><div className="contact-page-actions"><button type="button" className="button button-secondary" onClick={() => window.print()}>Print</button><button type="button" className="button button-primary" onClick={() => void exportCsv()}>Export CSV</button></div></header>{error ? <HelperText tone="error">{error}</HelperText> : null}<div className="catalog-toolbar card subtle-card"><select value={companyId} onChange={e => setCompanyId(e.target.value)}>{companies.map(x => <option key={x.id} value={x.id}>{x.name}</option>)}</select><input type="date" className="text-input" value={from} onChange={e => setFrom(e.target.value)} /><input type="date" className="text-input" value={to} onChange={e => setTo(e.target.value)} /></div>{report ? <section className="card"><div className="page-meta-row"><div className="page-meta-chips"><span className="page-meta-chip">Status <strong>{report.isBalanced ? "Balanced" : "Out of balance"}</strong></span><span className="page-meta-chip">Company <strong>{report.companyName}</strong></span></div></div><div className="table-scroll table-scroll-bounded"><table className="catalog-table"><thead><tr><th>Account</th><th>Type</th><th>Opening Dr</th><th>Opening Cr</th><th>Period Dr</th><th>Period Cr</th><th>Closing Dr</th><th>Closing Cr</th></tr></thead><tbody>{report.lines.length === 0 ? <EmptyTableRow colSpan={8} title="No posted journal activity" description="Post journal entries to produce a trial balance." /> : report.lines.map(x => <tr key={x.accountId}><td>{x.accountCode} · {x.accountName}</td><td>{x.accountType}</td><td>{formatCurrency(x.openingDebit, report.currency)}</td><td>{formatCurrency(x.openingCredit, report.currency)}</td><td>{formatCurrency(x.periodDebit, report.currency)}</td><td>{formatCurrency(x.periodCredit, report.currency)}</td><td>{formatCurrency(x.closingDebit, report.currency)}</td><td>{formatCurrency(x.closingCredit, report.currency)}</td></tr>)}</tbody><tfoot><tr><th colSpan={2}>Totals</th><th>{formatCurrency(report.totalOpeningDebit, report.currency)}</th><th>{formatCurrency(report.totalOpeningCredit, report.currency)}</th><th>{formatCurrency(report.totalPeriodDebit, report.currency)}</th><th>{formatCurrency(report.totalPeriodCredit, report.currency)}</th><th>{formatCurrency(report.totalClosingDebit, report.currency)}</th><th>{formatCurrency(report.totalClosingCredit, report.currency)}</th></tr></tfoot></table></div></section> : <section className="card"><p className="muted">Loading trial balance...</p></section>}</div>;
}
